server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/ArquiDogs
    username: postgres
    password: jose
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: localhost
    port: 1025
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
dogApi:
  url: https://dog.ceo/api/breeds/image/random

